name: build
on: [push]
jobs:
  run:
    name: build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
          #- windows-latest
        ocaml-compiler:
          - 4.08.x
          - 4.12.x
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        opam-depext: false
    - run: opam pin -y -n .
    - run: opam depext -yt quip
    - run: opam install -t . --deps-only
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
      if: ${{ matrix.os == 'ubuntu-latest'}}
